import type { Filters } from "./queries";
// Search-friendly collection pages: /egypt-tours/<slug>. Each has its own copy, so they are useful pages, not thin duplicates.
export type Landing = { slug: string; title: string; h1: string; description: string; eyebrow: string; filter: Filters; intro: string[]; points: string[]; faqs: [string, string][]; fallbackNote?: string };
export const LANDINGS: Landing[] = [
  { slug: "private-tours-egypt", eyebrow: "Private tours", h1: "Private tours in Egypt", title: "Private Egypt Tours: Your Own Guide, Driver & Hotel Pickup", description: "Book private tours in Egypt with your own Egyptologist guide and driver. Private Giza pyramids, Cairo, Luxor and Aswan tours with hotel pickup and flexible timing.", filter: { type: "private" },
    intro: ["A private tour in Egypt means the day is yours. You get your own guide and driver, hotel pickup, and the freedom to spend longer where you like and skip what you don't. It is the easiest way to see the Giza pyramids, Cairo, Luxor and Aswan without queues of tour buses or rigid schedules.", "Our private Egypt tours are run by a local team with more than ten years of experience. We plan the timing around crowds and heat, and we're on WhatsApp before and during your trip."],
    points: ["Your own Egyptologist guide and air-conditioned vehicle", "Hotel pickup and drop-off included on most tours", "Flexible pace, ideal for families, couples and small groups", "50% deposit to confirm, the rest before you travel"],
    faqs: [["How much does a private tour in Egypt cost?", "Prices depend on the tour and group size. Each tour page shows the price for your group before you book, with what is included."], ["Is a private tour worth it in Egypt?", "Many travellers find it is. A private guide lets you visit at quieter times, set the pace and ask as many questions as you like."], ["Can I customise a private Egypt tour?", "Yes. Use our trip planner or message us on WhatsApp and we will adjust the route, timing and stops."]] },
  { slug: "family-tours-egypt", eyebrow: "Family tours", h1: "Family tours in Egypt", title: "Family Tours in Egypt: Kid-Friendly Pyramids & Nile Trips", description: "Family-friendly Egypt tours with guides who keep kids engaged. Private pyramids tours, the Grand Egyptian Museum and easy-paced days with hotel pickup.", filter: { audience: "FAMILY" },
    intro: ["Egypt is a great family destination when the days are paced properly. Our family tours use guides who tell the stories of the pharaohs in a way children enjoy, with breaks, snacks and time to explore.", "We arrange private vehicles with hotel pickup, so you are not carrying tired kids through crowds. Children's prices and infant policies are shown when you book."],
    points: ["Guides who bring history to life for children", "Private vehicles, flexible breaks and easy pacing", "Child prices and free infants shown up front", "Simple booking with a 50% deposit"],
    faqs: [["Is Egypt suitable for children?", "Yes. With shorter days, plenty of water and a private guide, many families enjoy Egypt with children of all ages."], ["What is the best family tour in Egypt?", "A private Giza pyramids and Grand Egyptian Museum day is a popular first choice for families."], ["Do children get a discount?", "Yes. Children's prices apply and infants are free on most tours. You will see the total before you confirm."]] },
  { slug: "honeymoon-tours-egypt", eyebrow: "Couples and honeymoon", h1: "Honeymoon and couples tours in Egypt", title: "Egypt Honeymoon & Couples Tours: Romantic Nile & Luxor Trips", description: "Romantic Egypt tours for couples and honeymooners: sunrise balloon flights over Luxor, private pyramids tours and Nile experiences.", filter: { audience: "COUPLE" },
    intro: ["Egypt is made for couples: sunrise over the temples of Luxor from a hot air balloon, private guides at the pyramids, and slow evenings on the Nile.", "We can build a romantic Egypt itinerary for two, from a short Cairo and Luxor escape to a longer honeymoon with Nile cruise and Red Sea days."],
    points: ["Sunrise hot air balloon flights over Luxor", "Private guides and drivers, just for the two of you", "Custom itineraries with hotels chosen for couples", "Clear prices and a 50% deposit"],
    faqs: [["What is the best honeymoon itinerary in Egypt?", "Many couples combine Cairo, Luxor and Aswan, with a Nile cruise or a sunrise balloon flight over Luxor."], ["Can you arrange romantic extras?", "Yes. Tell us about your occasion and we can arrange private dinners, photographers and special touches."], ["How far ahead should we book?", "Book early for winter, when Luxor balloons and Nile cruises are busiest."]] },
  { slug: "nile-cruises-egypt", eyebrow: "Nile cruises", h1: "Nile cruises in Egypt", title: "Nile Cruises Egypt: Luxor to Aswan 3, 4 & 5 Night Cruises", description: "Book a Nile cruise from Luxor to Aswan with temples, meals and guided visits included. Multi-day Egypt packages that combine Cairo with a Nile cruise.", filter: { category: "NILE_CRUISE" }, fallbackNote: "Nile cruise packages are arranged on request. Here are our multi-day Egypt packages, and we can add a Nile cruise to any of them.",
    intro: ["A Nile cruise is the most relaxing way to see Upper Egypt. You unpack once, sail between Luxor and Aswan, and visit Karnak, the Valley of the Kings, Edfu, Kom Ombo and Philae along the way.", "We can arrange three, four or five night Nile cruises, on their own or combined with Cairo and the Giza pyramids. Tell us your dates and budget and we will send options."],
    points: ["Temples, meals and guided visits included in most packages", "Combine with Cairo for the complete Egypt itinerary", "Private transfers and domestic flights arranged for you", "50% deposit to confirm"],
    faqs: [["How long is a Nile cruise from Luxor to Aswan?", "Most Nile cruises run three or four nights, with a five night option for a slower pace."], ["What is included in a Nile cruise?", "Typically your cabin, meals, guided sightseeing and transfers. Drinks and tips are usually extra, and your quote lists exactly what is included."], ["When is the best time for a Nile cruise?", "October to April is the most comfortable period. Book early for winter."]] },
  { slug: "day-tours-egypt", eyebrow: "Day tours", h1: "Egypt day tours", title: "Egypt Day Tours: Giza Pyramids, Cairo, Luxor & Aswan Day Trips", description: "Egypt day tours and day trips: Giza pyramids and Sphinx, Old Cairo, Luxor East and West Bank and Aswan's Philae and Abu Simbel. Private or shared with hotel pickup.", filter: { category: "DAY" },
    intro: ["If you have a day or two, an Egypt day tour is the best way to see the highlights. Our day trips cover the Giza pyramids and Sphinx, Old Cairo, Luxor's temples and tombs, and Aswan's Philae Temple and Abu Simbel.", "Most day tours include hotel pickup, a local guide and an air-conditioned vehicle. Choose private for flexibility or shared for value."],
    points: ["Hotel pickup on most day tours", "Local guides and comfortable vehicles", "Private or shared options", "See the total price before you book"],
    faqs: [["What is the best day tour in Egypt?", "For most first-time visitors, the Giza pyramids and Sphinx is the essential day tour."], ["Can I do the pyramids and museum in one day?", "Yes. A combined day covers the Giza pyramids and the Grand Egyptian Museum comfortably."], ["Do day tours include lunch and tickets?", "Each tour page lists what is included. Entrance fees and lunch are often extra, and we show them clearly."]] },
  { slug: "egypt-tour-packages", eyebrow: "Tour packages", h1: "Egypt tour packages", title: "Egypt Tour Packages: Multi-Day Cairo, Luxor & Aswan Tours", description: "Multi-day Egypt tour packages with hotels, guides, transfers and domestic flights. Cairo and Luxor, Nile cruise combinations and custom itineraries.", filter: { category: "MULTI_DAY" },
    intro: ["An Egypt tour package takes care of hotels, transfers, guides, entrance fees and internal flights in one clear price. Choose a ready-made itinerary, such as Cairo and Luxor in five days, or ask us to tailor one.", "Packages can include a Nile cruise, the Grand Egyptian Museum and beach time on the Red Sea. Our team confirms the details on your quote."],
    points: ["Hotels, transfers and guides arranged together", "Domestic flights and entrance fees on request", "Custom itineraries for couples, families and friends", "50% deposit to confirm, balance before travel"],
    faqs: [["How many days do you need for Egypt?", "Five days covers Cairo and Luxor, seven days adds Aswan, and ten days lets you add a Nile cruise or the Red Sea."], ["What is included in an Egypt tour package?", "Usually hotels, transfers, guides and tours, and often internal flights. Your quote lists exactly what is included."], ["Can I customise a package?", "Yes. Every package can be adjusted, or we can build one from scratch with our trip planner."]] },
  { slug: "cairo-airport-transfers", eyebrow: "Airport transfers", h1: "Cairo airport transfers", title: "Cairo Airport Transfer: Private Meet & Greet at CAI", description: "Private Cairo airport transfers with meet and greet at arrivals, flight tracking and a fixed price to your hotel in Cairo or Giza.", filter: { category: "TRANSFER" },
    intro: ["Start your Egypt trip stress-free with a private Cairo airport transfer. Your driver meets you at arrivals with your name, helps with bags and takes you straight to your hotel in Cairo or Giza.", "We track your flight, so delays are not a problem, and the price is fixed and agreed before you travel."],
    points: ["Meet and greet at Cairo International Airport (CAI)", "Flight tracking, so no waiting charges for delays", "Fixed price agreed in advance", "Easy to add to any tour or package"],
    faqs: [["How do I find my driver at Cairo airport?", "Your driver waits at arrivals with a sign showing your name, and we send you their details on WhatsApp before you land."], ["How long is the transfer from Cairo airport to Giza?", "It usually takes 45 to 90 minutes depending on traffic."], ["Can I book a transfer back to the airport?", "Yes. Add a departure transfer to your booking and we will arrange pickup at your hotel."]] },
];
export const landingBySlug = (slug: string) => LANDINGS.find((l) => l.slug === slug);
