import { db, schema as s } from "./index";
import { eq } from "drizzle-orm";

// One-time content upgrade: search-friendly destination pages, more travel guides, and better Google titles for the demo tours.
// Runs once (tracked in settings). Tours you created or edited yourself are never overwritten.
type Dest = { slug: string; tagline: string; overview: string; bestTime: string; howToGet: string; whereToStay: string; tips: string; recommendedDays: string; seoTitle: string; seoDescription: string };
const DEST: Dest[] = [
  { slug: "cairo", tagline: "Egypt's capital: museums, mosques and markets", recommendedDays: "2 to 3 days",
    overview: "Cairo is where most Egypt tours begin. Explore Islamic Cairo's mosques and the Khan el-Khalili bazaar, walk through Coptic Cairo's ancient churches, and see the treasures of the Grand Egyptian Museum. On a private Cairo tour, a local guide handles the traffic, tickets and timing so you see more in less time. Most travellers combine Cairo with the Giza pyramids, Saqqara and a flight south to Luxor and Aswan.",
    bestTime: "October to April is the best time to visit Cairo, with mild days that suit sightseeing. Summer (June to August) is very hot, so start early and plan a break in the afternoon.",
    howToGet: "Fly into Cairo International Airport (CAI). We arrange private Cairo airport transfers with a driver who tracks your flight and meets you at arrivals.",
    whereToStay: "Zamalek and downtown suit cafes, museums and evening walks. Hotels in Giza give you pyramid views and quicker access to the plateau.",
    tips: "Start sightseeing early to beat heat and traffic, carry small notes for tips, and let your guide handle street vendors. Dress modestly when visiting mosques.",
    seoTitle: "Cairo Tours & Things to Do: Private Cairo Day Tours", seoDescription: "Plan your Cairo trip: private Cairo day tours, Islamic and Coptic Cairo, Khan el-Khalili and the Grand Egyptian Museum. Best time to visit and where to stay." },
  { slug: "giza", tagline: "The Great Pyramids and the Sphinx", recommendedDays: "Half to full day",
    overview: "The Giza Plateau is home to the Great Pyramid of Khufu, the pyramids of Khafre and Menkaure, and the Great Sphinx. A private Giza pyramids tour with an Egyptologist guide lets you pick the best viewpoints, avoid the busiest hours and understand what you are looking at. The Grand Egyptian Museum is close by, so many travellers pair the pyramids and the museum in a single day.",
    bestTime: "Arrive at opening time in any season for cooler air and fewer crowds. October to April is the most comfortable period.",
    howToGet: "Giza is about 30 to 60 minutes from central Cairo by car, depending on traffic. A private driver or hotel pickup is the easiest way to get there.",
    whereToStay: "Hotels near the plateau offer early access and pyramid views. Central Cairo gives you more restaurants and evening options.",
    tips: "Wear a hat and comfortable shoes, carry water, and agree camel or horse rides with your guide before you go. Entering the pyramids is a separate ticket.",
    seoTitle: "Giza Pyramids Tour: Private Pyramids & Sphinx Day Tours", seoDescription: "Book a private Giza pyramids and Sphinx tour with an Egyptologist guide. Hotel pickup, best viewpoints and less waiting. Best time to visit Giza." },
  { slug: "luxor", tagline: "The world's greatest open-air museum", recommendedDays: "2 to 3 days",
    overview: "Luxor is ancient Thebes, home to Karnak Temple, Luxor Temple, the Valley of the Kings, Hatshepsut's temple and the Colossi of Memnon. Give Luxor at least two days: the East Bank temples on one, the West Bank tombs on the other. Luxor tours can also include a sunrise hot air balloon flight over the temples, and Luxor is where many Nile cruises to Aswan begin.",
    bestTime: "November to February is the best time to visit Luxor. Summers are extremely hot, so tomb visits should be at first light.",
    howToGet: "Fly from Cairo to Luxor in about an hour, take the overnight train, or arrive by Nile cruise from Aswan.",
    whereToStay: "The East Bank is best for restaurants and walking to the temples. The West Bank is quieter and gives you balloon and sunrise views.",
    tips: "Book a sunrise hot air balloon the day before your tomb visits so you are not rushed. Bring a hat, water and a light layer for cool mornings.",
    seoTitle: "Luxor Tours: Valley of the Kings, Karnak & Balloon Flights", seoDescription: "Luxor day tours and packages: Valley of the Kings, Karnak, Luxor Temple and sunrise hot air balloons. Private or shared. Best time to visit Luxor." },
  { slug: "aswan", tagline: "Slow Nile, Nubian colour", recommendedDays: "2 days",
    overview: "Aswan is calmer than Cairo or Luxor. See Philae Temple by boat, sail a felucca around Elephantine Island, visit a Nubian village and take the early road to Abu Simbel. Aswan is also where many Nile cruises from Luxor finish, so it pairs well with a cruise or a Cairo, Luxor and Aswan package.",
    bestTime: "October to March. The rest of the year is very hot, so plan sightseeing for the early morning.",
    howToGet: "Fly from Cairo or Luxor, or arrive by Nile cruise. Aswan Airport is the gateway for Abu Simbel.",
    whereToStay: "Along the Corniche for Nile views, or on Elephantine Island for a quieter stay.",
    tips: "The Abu Simbel road trip starts very early, so plan a rest afternoon afterwards.",
    seoTitle: "Aswan Tours: Philae Temple, Abu Simbel & Nubian Village", seoDescription: "Aswan tours and day trips: Philae Temple, Abu Simbel, felucca rides and Nubian villages. Combine with a Nile cruise. Best time to visit." },
  { slug: "alexandria", tagline: "Egypt by the Mediterranean", recommendedDays: "1 to 2 days",
    overview: "Alexandria is a sea-breeze contrast to Cairo. Visit the Bibliotheca Alexandrina, the Qaitbay Citadel, the Roman catacombs and Pompey's Pillar, then eat fresh seafood on the corniche. It works well as a long day trip from Cairo, or as an overnight stop if you want to enjoy the evenings by the sea.",
    bestTime: "April to June and September to November are the most pleasant months. Summer is busy with local holidaymakers.",
    howToGet: "About 2.5 to 3 hours from Cairo by road. Trains also run between Cairo and Alexandria.",
    whereToStay: "Along the corniche in the city centre, close to the sea and restaurants.",
    tips: "Go early in summer, and try the local seafood restaurants near the harbour.",
    seoTitle: "Alexandria Tours: Day Trip from Cairo & Things to Do", seoDescription: "Alexandria day tours from Cairo: Bibliotheca Alexandrina, Qaitbay Citadel, catacombs and seafood by the Mediterranean. Best time to visit and how long to stay." },
  { slug: "hurghada", tagline: "Red Sea reefs and desert adventures", recommendedDays: "3 to 5 days",
    overview: "Hurghada is a Red Sea base for snorkelling and diving trips to the Giftun Islands, plus desert safaris by quad or jeep. Nearby El Gouna and Sahl Hasheesh offer polished resorts. Many travellers finish a Cairo and Luxor trip with a few days of beach time in Hurghada.",
    bestTime: "Year-round. The sea is warmest from June to October and the air is most comfortable in spring and autumn.",
    howToGet: "Direct flights arrive from Europe and Cairo. By road, Luxor to Hurghada takes about four to five hours.",
    whereToStay: "El Gouna for a polished resort town, Sahl Hasheesh for beach resorts, central Hurghada for good value.",
    tips: "Bring reef-safe sunscreen and confirm boat size and lunch when you book a snorkelling trip.",
    seoTitle: "Hurghada Tours: Red Sea Snorkelling, Diving & Desert Safari", seoDescription: "Hurghada tours and Red Sea trips: Giftun Islands snorkelling, diving and desert safaris. Best time to visit and where to stay." },
];

type G = { slug: string; title: string; cluster: string; summary: string; destinationSlug: string | null; seoTitle: string; seoDescription: string; body: string };
const GUIDES: G[] = [
  { slug: "best-time-to-visit-egypt", title: "Best Time to Visit Egypt", cluster: "Egypt Travel Guide", destinationSlug: "cairo", summary: "Month-by-month advice for Cairo, Luxor, Aswan and the Red Sea.",
    seoTitle: "Best Time to Visit Egypt: Weather by Month & Season Guide", seoDescription: "The best time to visit Egypt for sightseeing, Nile cruises and the Red Sea, with weather by season for Cairo, Luxor, Aswan and Hurghada.",
    body: "The best time to visit Egypt is October to April, when Cairo, Luxor and Aswan are comfortable for sightseeing.\n\n## Egypt weather by season\nWinter (December to February) is sunny and cool in Cairo and warm in Luxor and Aswan. It is the most popular season for Egypt tours and Nile cruises, so book early. Spring and autumn are warm and ideal for pyramids tours and Cairo day trips.\n\nSummer (June to August) is hot, especially in Upper Egypt. If you travel then, visit temples and tombs at sunrise and rest in the afternoon.\n\n## Red Sea and beach weather\nHurghada, Sharm El Sheikh and Dahab are good all year. The sea is warmest from June to October.\n\n## Busy periods\nChristmas, New Year and Easter are the busiest times. Book Luxor hotels and Nile cruises well in advance." },
  { slug: "egypt-visa-guide", title: "Egypt Visa Guide for Tourists", cluster: "Egypt Travel Guide", destinationSlug: null, summary: "How tourist visas work for most visitors, and what to check before you fly.",
    seoTitle: "Egypt Visa for Tourists: E-Visa, Visa on Arrival & Requirements", seoDescription: "How to get an Egypt tourist visa: e-visa, visa on arrival and what to check before you travel. Passport validity, fees and airport transfer tips.",
    body: "Many nationalities can get an Egypt tourist visa on arrival or through the official e-visa portal. Rules and fees change and depend on your passport, so always confirm current requirements before you fly.\n\n## What to check before you travel\nCheck Egypt's official e-visa website or your nearest embassy for your nationality. Your passport should have at least six months of validity, and it is worth carrying a printed copy of your booking and hotel details.\n\n## Arriving in Egypt\nIf you booked an airport transfer with us, share your flight number. We track your flight so your driver is waiting when you clear immigration.\n\n## Extending your stay\nIf you plan to stay longer, ask us early so we can help you plan your route and paperwork." },
  { slug: "egypt-3-day-itinerary", title: "Egypt in 3 Days: A Cairo Itinerary", cluster: "Itineraries", destinationSlug: "cairo", summary: "A realistic first-timer's plan for a short stop in Cairo.",
    seoTitle: "Egypt 3-Day Itinerary: Cairo, Giza Pyramids & Old Cairo", seoDescription: "A practical 3-day Egypt itinerary: Giza pyramids, the Grand Egyptian Museum, Old Cairo, Khan el-Khalili and a day trip to Saqqara or Alexandria.",
    body: "Three days is enough to see the highlights of Cairo and Giza without rushing.\n\n## Day 1: Giza pyramids and Sphinx\nStart early at the Giza Plateau for the Great Pyramid, the panoramic viewpoint and the Sphinx. In the afternoon visit the Grand Egyptian Museum.\n\n## Day 2: Old Cairo\nExplore Coptic Cairo, Islamic Cairo and Khan el-Khalili bazaar. It is a great day for food, markets and history.\n\n## Day 3: Saqqara and Memphis, or Alexandria\nChoose an early trip to Saqqara and Memphis to see where pyramid building began, or take a day trip to Alexandria on the Mediterranean.\n\nWant to add Luxor? A 5-day Cairo and Luxor package fits more in without rushing." },
  { slug: "egypt-7-day-itinerary", title: "Egypt in 7 Days: Cairo, Luxor & Aswan", cluster: "Itineraries", destinationSlug: "luxor", summary: "A one-week Egypt itinerary covering the pyramids, Luxor's temples and Aswan.",
    seoTitle: "Egypt 7-Day Itinerary: Cairo, Luxor & Aswan Highlights", seoDescription: "The best 7 day Egypt itinerary: Cairo and the Giza pyramids, a flight to Luxor for the Valley of the Kings, and Aswan for Philae Temple and Abu Simbel.",
    body: "One week is the classic way to see Egypt's highlights: the pyramids, Luxor's temples and tombs, and Aswan.\n\n## Days 1 to 3: Cairo and Giza\nArrive in Cairo, then spend two days on the Giza pyramids, the Grand Egyptian Museum, Old Cairo and Khan el-Khalili.\n\n## Days 4 and 5: Luxor\nFly to Luxor. Spend one day on the West Bank (Valley of the Kings and Hatshepsut Temple) and one on the East Bank (Karnak and Luxor Temple). A sunrise hot air balloon is a great addition.\n\n## Days 6 and 7: Aswan\nFly or sail to Aswan for Philae Temple and a felucca ride, with an early Abu Simbel day trip if you have time.\n\nPrefer to sail? A Nile cruise between Luxor and Aswan covers the same temples with a floating hotel." },
  { slug: "giza-pyramids-visitor-guide", title: "Giza Pyramids Visitor Guide: Tickets, Timing & Tips", cluster: "Cairo & Giza", destinationSlug: "giza", summary: "How to visit the Giza pyramids and Sphinx without the stress.",
    seoTitle: "Giza Pyramids Visitor Guide: Tickets, Best Time & Tips", seoDescription: "How to visit the Giza pyramids: best time of day, tickets for the pyramids and Sphinx, what to wear, and why a private guide makes the day easier.",
    body: "The Giza pyramids are the most visited sight in Egypt, and a little planning makes the visit far more enjoyable.\n\n## Best time to visit the pyramids\nArrive at opening time. The air is cooler, the light is soft and the crowds are smaller. Late afternoon is a good second option.\n\n## Tickets and entry\nThere is an entrance ticket for the Giza Plateau, and separate tickets to enter individual pyramids and other sites. A guide can explain what is worth the extra ticket for you.\n\n## Camels, horses and street sellers\nAgree any camel or horse ride with your guide beforehand, and politely decline unwanted offers. A private guide handles all of this for you.\n\n## What to wear\nComfortable shoes, a hat, sunscreen and water. Modest, breathable clothes work best.\n\nCombine the pyramids with the Grand Egyptian Museum for a full day." },
  { slug: "nile-cruise-guide-luxor-aswan", title: "Nile Cruise Guide: Luxor to Aswan", cluster: "Nile & Luxor", destinationSlug: "aswan", summary: "What a Nile cruise includes, the stops along the way, and how to choose.",
    seoTitle: "Nile Cruise Guide: Luxor to Aswan Itinerary, Stops & Tips", seoDescription: "Everything about a Nile cruise from Luxor to Aswan: typical 3 and 4 night itineraries, stops at Edfu and Kom Ombo, what is included and how to choose.",
    body: "A Nile cruise is one of the most relaxing ways to see the temples of Upper Egypt. You unpack once, sail between Luxor and Aswan, and visit the sights each day.\n\n## Typical Nile cruise itinerary\nMost cruises run three or four nights between Luxor and Aswan. Along the way you visit Karnak and Luxor Temple, the Valley of the Kings, the Temple of Horus at Edfu, the Temple of Kom Ombo and Philae Temple in Aswan.\n\n## What is usually included\nAccommodation on the ship, meals, guided visits and transfers. Drinks and tips are usually extra, so check what your package includes.\n\n## Combine it with Cairo\nMany travellers add two or three days in Cairo before the cruise for the pyramids and the Grand Egyptian Museum." },
  { slug: "egypt-currency-money-and-tipping", title: "Egypt Currency, Money & Tipping Guide", cluster: "Egypt Travel Guide", destinationSlug: null, summary: "Cash, cards, ATMs and how tipping works in Egypt.",
    seoTitle: "Egypt Currency, Money & Tipping Guide for Tourists", seoDescription: "How money works in Egypt: the Egyptian pound, ATMs and cards, carrying small notes, and how tipping works for guides, drivers and restaurants.",
    body: "Egypt uses the Egyptian pound (EGP). Cards are accepted in hotels and many restaurants, but cash is useful for tips, markets and small purchases.\n\n## Cash and ATMs\nATMs are easy to find in cities and at airports. Carry small notes, as change can be hard to find at busy sights.\n\n## Tipping in Egypt\nTipping (often called baksheesh) is customary for guides, drivers, hotel staff and restaurants. Ask your guide what is usual for your trip, and keep small notes ready.\n\n## Paying for your tour\nWith Egypt Knight Tours you pay a 50% deposit to confirm your booking, and settle the rest before travel, so you carry less cash on the day." },
  { slug: "is-egypt-safe-for-tourists", title: "Is Egypt Safe for Tourists? Travel Tips", cluster: "Egypt Travel Guide", destinationSlug: null, summary: "Practical safety advice for visiting Egypt, from a local team.",
    seoTitle: "Is Egypt Safe for Tourists? Practical Safety Tips", seoDescription: "Is Egypt safe to visit? Practical tips for tourists: choosing a trusted local operator, travelling with a guide, avoiding scams and staying healthy.",
    body: "Millions of visitors travel around Egypt every year, and most trips are trouble-free. A few sensible habits make yours smoother.\n\n## Travel with a trusted local team\nA local guide and driver handle logistics, know which places to go at which times, and help you avoid common tourist annoyances.\n\n## Everyday tips\nUse licensed taxis or apps, agree prices in advance, drink bottled water, and keep valuables out of sight. Dress modestly at religious sites.\n\n## Check official advice\nAlways check your government's current travel advice before you go, and keep our WhatsApp number handy during your trip." },
  { slug: "egypt-dress-code-and-etiquette", title: "What to Wear in Egypt: Dress Code & Etiquette", cluster: "Egypt Travel Guide", destinationSlug: null, summary: "What to pack and how to dress for temples, mosques and hot days.",
    seoTitle: "What to Wear in Egypt: Dress Code, Packing & Etiquette", seoDescription: "What to wear in Egypt as a tourist: light, modest clothes for temples and mosques, comfortable shoes, sun protection and simple etiquette tips.",
    body: "Egypt is warm and relaxed with tourists, but dressing thoughtfully helps you stay comfortable and respectful.\n\n## What to pack\nLight, breathable clothes that cover shoulders and knees, comfortable walking shoes, a hat, sunglasses and sunscreen. Add a light layer for cool mornings and evenings in winter.\n\n## Mosques and religious sites\nCover shoulders and knees, and women should carry a light scarf. You will remove shoes at mosques.\n\n## Beaches and resorts\nBeachwear is fine at resorts and on boats in the Red Sea, but cover up in towns and markets." },
];
const TOUR_SEO: Record<string, [string, string]> = {
  "giza-pyramids-sphinx-day-tour": ["Giza Pyramids & Sphinx Day Tour from Cairo | Private or Shared", "Visit the Giza pyramids and Sphinx with an Egyptologist guide. Hotel pickup in Cairo and Giza, the best viewpoints and timing. Private or shared Giza pyramids tour."],
  "grand-egyptian-museum-pyramids-private-day": ["Grand Egyptian Museum & Pyramids Private Day Tour", "A private family-friendly day: the Grand Egyptian Museum in the morning and the Giza pyramids in the afternoon, with a private guide and vehicle."],
  "cairo-old-town-coptic-islamic-khan-el-khalili": ["Old Cairo Tour: Coptic Cairo, Islamic Cairo & Khan el-Khalili", "Explore Coptic Cairo's churches, Islamic Cairo's mosques and the Khan el-Khalili bazaar on a guided Old Cairo day tour."],
  "luxor-east-and-west-bank-day-tour": ["Luxor Day Tour: Valley of the Kings, Karnak & Hatshepsut", "See Luxor's East and West Bank in one day: Valley of the Kings, Hatshepsut Temple, Karnak and Luxor Temple with a local guide."],
  "luxor-sunrise-hot-air-balloon": ["Luxor Sunrise Hot Air Balloon Ride Over the Temples", "Float over Luxor's West Bank temples at sunrise on a hot air balloon flight, with hotel pickup. A favourite for couples and honeymooners."],
  "aswan-philae-and-abu-simbel-day": ["Aswan Day Tour: Philae Temple & Abu Simbel", "A long, rewarding day in Aswan: Abu Simbel's giant temples of Ramses II and Philae Temple by boat, with a local guide."],
  "5-day-cairo-and-luxor-package": ["5-Day Egypt Package: Cairo Pyramids & Luxor Temples", "A 5-day Egypt tour package with the Giza pyramids, museums and Luxor's temples, including domestic flights, hotels and transfers on request."],
  "cairo-airport-transfer": ["Cairo Airport Private Transfer | Meet & Greet at CAI", "Private Cairo airport transfer with meet and greet at arrivals, flight tracking and a fixed price to your hotel in Cairo or Giza."],
};

export async function applyContentV2() {
  const [flag] = await db.select().from(s.settings).where(eq(s.settings.key, "content.version")); if (flag && Number(flag.value) >= 2) return;
  for (const d of DEST) { const { slug, ...rest } = d; await db.update(s.destinations).set(rest).where(eq(s.destinations.slug, slug)); }
  for (const g of GUIDES) {
    const ex = await db.select().from(s.guides).where(eq(s.guides.slug, g.slug));
    if (ex.length) await db.update(s.guides).set({ ...g, status: "PUBLISHED" }).where(eq(s.guides.slug, g.slug)); else await db.insert(s.guides).values({ ...g, status: "PUBLISHED" });
  }
  for (const [slug, [t, d]] of Object.entries(TOUR_SEO)) {
    const [tour] = await db.select().from(s.tours).where(eq(s.tours.slug, slug)); if (!tour) continue;
    if (tour.seoTitle === `${tour.title} | Egypt Knight`.slice(0, 70) || !tour.seoTitle) await db.update(s.tours).set({ seoTitle: t.slice(0, 70), seoDescription: d.slice(0, 168) }).where(eq(s.tours.slug, slug));
  }
  if (flag) await db.update(s.settings).set({ value: "2" }).where(eq(s.settings.key, "content.version")); else await db.insert(s.settings).values({ key: "content.version", value: "2" });
}
