// Generated from drizzle/0000_init.sql (npm run db:sql). Do not edit by hand.
export const MIGRATION: string[] = [
 "CREATE TABLE `addons` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`tour_id` text NOT NULL,\n\t`name` text NOT NULL,\n\t`description` text DEFAULT '' NOT NULL,\n\t`price` real NOT NULL,\n\t`unit` text DEFAULT 'PER_BOOKING' NOT NULL,\n\t`active` integer DEFAULT true NOT NULL,\n\tFOREIGN KEY (`tour_id`) REFERENCES `tours`(`id`) ON UPDATE no action ON DELETE cascade\n);",
 "CREATE TABLE `analytics_events` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`name` text NOT NULL,\n\t`session_id` text,\n\t`path` text,\n\t`tour_slug` text,\n\t`props` text,\n\t`created_at` integer DEFAULT (unixepoch()) NOT NULL\n);",
 "CREATE INDEX `analytics_name_idx` ON `analytics_events` (`name`,`created_at`);",
 "CREATE TABLE `audit_logs` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`user_id` text,\n\t`action` text NOT NULL,\n\t`entity` text NOT NULL,\n\t`entity_id` text,\n\t`created_at` integer DEFAULT (unixepoch()) NOT NULL,\n\tFOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action\n);",
 "CREATE TABLE `booking_events` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`booking_id` text NOT NULL,\n\t`type` text NOT NULL,\n\t`note` text,\n\t`created_at` integer DEFAULT (unixepoch()) NOT NULL,\n\tFOREIGN KEY (`booking_id`) REFERENCES `bookings`(`id`) ON UPDATE no action ON DELETE cascade\n);",
 "CREATE TABLE `bookings` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`ref` text NOT NULL,\n\t`status` text DEFAULT 'PENDING' NOT NULL,\n\t`tour_id` text NOT NULL,\n\t`customer_id` text NOT NULL,\n\t`travel_date` text NOT NULL,\n\t`adults` integer NOT NULL,\n\t`children` integer DEFAULT 0 NOT NULL,\n\t`infants` integer DEFAULT 0 NOT NULL,\n\t`is_private` integer DEFAULT false NOT NULL,\n\t`hotel` text,\n\t`pickup_location` text,\n\t`special_requests` text,\n\t`dietary` text,\n\t`accessibility` text,\n\t`addons_json` text DEFAULT '[]' NOT NULL,\n\t`subtotal` real NOT NULL,\n\t`discount` real DEFAULT 0 NOT NULL,\n\t`total` real NOT NULL,\n\t`deposit` real DEFAULT 0 NOT NULL,\n\t`pay_mode` text DEFAULT 'DEPOSIT' NOT NULL,\n\t`currency` text DEFAULT 'USD' NOT NULL,\n\t`coupon_id` text,\n\t`source` text,\n\t`created_at` integer DEFAULT (unixepoch()) NOT NULL,\n\tFOREIGN KEY (`tour_id`) REFERENCES `tours`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`customer_id`) REFERENCES `customers`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`coupon_id`) REFERENCES `coupons`(`id`) ON UPDATE no action ON DELETE no action\n);",
 "CREATE UNIQUE INDEX `bookings_ref_unique` ON `bookings` (`ref`);",
 "CREATE TABLE `coupons` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`code` text NOT NULL,\n\t`type` text NOT NULL,\n\t`value` real NOT NULL,\n\t`min_subtotal` real DEFAULT 0 NOT NULL,\n\t`tour_id` text,\n\t`expires_at` integer,\n\t`max_uses` integer,\n\t`used_count` integer DEFAULT 0 NOT NULL,\n\t`first_booking_only` integer DEFAULT false NOT NULL,\n\t`active` integer DEFAULT true NOT NULL\n);",
 "CREATE UNIQUE INDEX `coupons_code_unique` ON `coupons` (`code`);",
 "CREATE TABLE `customers` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`email` text NOT NULL,\n\t`name` text NOT NULL,\n\t`phone` text,\n\t`whatsapp` text,\n\t`country` text,\n\t`created_at` integer DEFAULT (unixepoch()) NOT NULL\n);",
 "CREATE UNIQUE INDEX `customers_email_unique` ON `customers` (`email`);",
 "CREATE TABLE `destinations` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`slug` text NOT NULL,\n\t`name` text NOT NULL,\n\t`tagline` text NOT NULL,\n\t`overview` text NOT NULL,\n\t`best_time` text NOT NULL,\n\t`how_to_get` text NOT NULL,\n\t`where_to_stay` text NOT NULL,\n\t`tips` text NOT NULL,\n\t`recommended_days` text NOT NULL,\n\t`seo_title` text NOT NULL,\n\t`seo_description` text NOT NULL\n);",
 "CREATE UNIQUE INDEX `destinations_slug_unique` ON `destinations` (`slug`);",
 "CREATE TABLE `follow_ups` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`lead_id` text NOT NULL,\n\t`template_key` text NOT NULL,\n\t`channel` text DEFAULT 'EMAIL' NOT NULL,\n\t`due_at` integer NOT NULL,\n\t`status` text DEFAULT 'SCHEDULED' NOT NULL,\n\tFOREIGN KEY (`lead_id`) REFERENCES `leads`(`id`) ON UPDATE no action ON DELETE cascade\n);",
 "CREATE TABLE `guides` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`slug` text NOT NULL,\n\t`title` text NOT NULL,\n\t`cluster` text NOT NULL,\n\t`summary` text NOT NULL,\n\t`body` text NOT NULL,\n\t`destination_slug` text,\n\t`seo_title` text NOT NULL,\n\t`seo_description` text NOT NULL,\n\t`status` text DEFAULT 'DRAFT' NOT NULL,\n\t`updated_at` integer DEFAULT (unixepoch()) NOT NULL\n);",
 "CREATE UNIQUE INDEX `guides_slug_unique` ON `guides` (`slug`);",
 "CREATE TABLE `lead_events` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`lead_id` text NOT NULL,\n\t`type` text NOT NULL,\n\t`note` text,\n\t`created_at` integer DEFAULT (unixepoch()) NOT NULL,\n\tFOREIGN KEY (`lead_id`) REFERENCES `leads`(`id`) ON UPDATE no action ON DELETE cascade\n);",
 "CREATE TABLE `leads` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`name` text NOT NULL,\n\t`email` text NOT NULL,\n\t`phone` text,\n\t`whatsapp` text,\n\t`country` text,\n\t`travel_dates` text,\n\t`travelers` integer,\n\t`interests` text,\n\t`budget` text,\n\t`message` text,\n\t`kind` text DEFAULT 'INQUIRY' NOT NULL,\n\t`source` text,\n\t`status` text DEFAULT 'NEW' NOT NULL,\n\t`tours_viewed` text,\n\t`notes` text,\n\t`consent_marketing` integer DEFAULT false NOT NULL,\n\t`assigned_to_id` text,\n\t`customer_id` text,\n\t`last_contact_at` integer,\n\t`next_follow_up_at` integer,\n\t`created_at` integer DEFAULT (unixepoch()) NOT NULL,\n\tFOREIGN KEY (`assigned_to_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`customer_id`) REFERENCES `customers`(`id`) ON UPDATE no action ON DELETE no action\n);",
 "CREATE TABLE `payments` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`booking_id` text NOT NULL,\n\t`provider` text DEFAULT 'MANUAL' NOT NULL,\n\t`kind` text NOT NULL,\n\t`amount` real NOT NULL,\n\t`status` text DEFAULT 'PENDING' NOT NULL,\n\t`provider_ref` text,\n\t`created_at` integer DEFAULT (unixepoch()) NOT NULL,\n\tFOREIGN KEY (`booking_id`) REFERENCES `bookings`(`id`) ON UPDATE no action ON DELETE no action\n);",
 "CREATE TABLE `reviews` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`tour_id` text NOT NULL,\n\t`author_name` text NOT NULL,\n\t`country` text,\n\t`rating` integer NOT NULL,\n\t`title` text NOT NULL,\n\t`body` text NOT NULL,\n\t`trip_date` text,\n\t`status` text DEFAULT 'PENDING' NOT NULL,\n\t`created_at` integer DEFAULT (unixepoch()) NOT NULL,\n\tFOREIGN KEY (`tour_id`) REFERENCES `tours`(`id`) ON UPDATE no action ON DELETE no action\n);",
 "CREATE TABLE `tours` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`slug` text NOT NULL,\n\t`title` text NOT NULL,\n\t`short_description` text NOT NULL,\n\t`long_description` text NOT NULL,\n\t`destination_id` text NOT NULL,\n\t`category` text NOT NULL,\n\t`audience` text DEFAULT 'ALL' NOT NULL,\n\t`duration_hours` integer DEFAULT 8 NOT NULL,\n\t`duration_days` integer DEFAULT 1 NOT NULL,\n\t`activity_level` text DEFAULT 'EASY' NOT NULL,\n\t`pricing_model` text DEFAULT 'PER_PERSON' NOT NULL,\n\t`price` real NOT NULL,\n\t`discount_price` real,\n\t`child_percent` integer DEFAULT 50 NOT NULL,\n\t`private_surcharge` real DEFAULT 0 NOT NULL,\n\t`is_private_available` integer DEFAULT true NOT NULL,\n\t`is_group_available` integer DEFAULT true NOT NULL,\n\t`max_travelers` integer DEFAULT 12 NOT NULL,\n\t`highlights` text DEFAULT '[]' NOT NULL,\n\t`itinerary` text DEFAULT '[]' NOT NULL,\n\t`included` text DEFAULT '[]' NOT NULL,\n\t`excluded` text DEFAULT '[]' NOT NULL,\n\t`pickup_info` text DEFAULT '' NOT NULL,\n\t`meeting_point` text DEFAULT '' NOT NULL,\n\t`what_to_bring` text DEFAULT '' NOT NULL,\n\t`cancellation_policy` text DEFAULT '' NOT NULL,\n\t`faqs` text DEFAULT '[]' NOT NULL,\n\t`image_url` text,\n\t`seo_title` text DEFAULT '' NOT NULL,\n\t`seo_description` text DEFAULT '' NOT NULL,\n\t`status` text DEFAULT 'DRAFT' NOT NULL,\n\t`popularity` integer DEFAULT 0 NOT NULL,\n\t`created_at` integer DEFAULT (unixepoch()) NOT NULL,\n\t`updated_at` integer DEFAULT (unixepoch()) NOT NULL,\n\tFOREIGN KEY (`destination_id`) REFERENCES `destinations`(`id`) ON UPDATE no action ON DELETE no action\n);",
 "CREATE UNIQUE INDEX `tours_slug_unique` ON `tours` (`slug`);",
 "CREATE TABLE `travelers` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`booking_id` text NOT NULL,\n\t`full_name` text NOT NULL,\n\t`type` text NOT NULL,\n\t`age` integer,\n\tFOREIGN KEY (`booking_id`) REFERENCES `bookings`(`id`) ON UPDATE no action ON DELETE cascade\n);",
 "CREATE TABLE `users` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`email` text NOT NULL,\n\t`name` text NOT NULL,\n\t`password_hash` text NOT NULL,\n\t`role` text DEFAULT 'SALES' NOT NULL,\n\t`created_at` integer DEFAULT (unixepoch()) NOT NULL\n);",
 "CREATE UNIQUE INDEX `users_email_unique` ON `users` (`email`);"
];

// Idempotent additions for databases created by an earlier version. Append new tables here as the schema grows.
export const EXTRA: string[] = [
 "CREATE TABLE IF NOT EXISTS `booking_events` (`id` text PRIMARY KEY NOT NULL, `booking_id` text NOT NULL, `type` text NOT NULL, `note` text, `created_at` integer DEFAULT (unixepoch()) NOT NULL, FOREIGN KEY (`booking_id`) REFERENCES `bookings`(`id`) ON UPDATE no action ON DELETE cascade)"
];
