import { db, schema as s } from "./index";
import bcrypt from "bcryptjs";
import { eq } from "drizzle-orm";

// DEMO CONTENT: prices, durations and inclusions are placeholders until Egypt Knight supplies real ones.
const dests = [
  { slug: "cairo", name: "Cairo", tagline: "Loud, layered, unforgettable", overview: "Cairo is where most Egypt trips start: Islamic Cairo's mosques and markets, Coptic Cairo's churches, and the Egyptian Museum, all within one enormous city. Give it at least two days.", bestTime: "October to April for comfortable weather. Summer is hot, so start early.", howToGet: "Fly into Cairo International Airport (CAI). Private transfers are the easiest way to your hotel.", whereToStay: "Zamalek for calm and cafes, downtown for history, Giza for pyramid views.", tips: "Carry small notes for tips, start sightseeing early, and agree the plan with your guide the day before.", recommendedDays: "2–3 days" },
  { slug: "giza", name: "Giza", tagline: "The pyramids, done properly", overview: "The Giza Plateau holds the Great Pyramid, the Sphinx and the Grand Egyptian Museum nearby. Going with a guide who plans around crowds and heat changes the whole day.", bestTime: "Go at opening time in any season to beat crowds and heat.", howToGet: "About 30–60 minutes from central Cairo depending on traffic. Private car with driver is simplest.", whereToStay: "Hotels near the plateau give early access; central Cairo gives more evening options.", tips: "Wear a hat and comfortable shoes. Be firm but polite with touts and let your guide handle camel and horse offers.", recommendedDays: "1 day" },
  { slug: "luxor", name: "Luxor", tagline: "The world's greatest open-air museum", overview: "Luxor holds Karnak, Luxor Temple, the Valley of the Kings and Hatshepsut's temple. Split it over two days: east bank temples, west bank tombs.", bestTime: "November to February is best. Summers are extremely hot, so tomb visits should be at first light.", howToGet: "Fly from Cairo (about 1 hour), or take the overnight train or a Nile cruise.", whereToStay: "East bank for restaurants and temples on foot; west bank for quiet and balloon views.", tips: "Book the hot air balloon for sunrise the day before your tombs visit so you are not rushed.", recommendedDays: "2–3 days" },
  { slug: "aswan", name: "Aswan", tagline: "Slow Nile, Nubian colour", overview: "Aswan is calmer than Cairo or Luxor: Philae Temple, felucca rides around Elephantine Island, a Nubian village and the road to Abu Simbel.", bestTime: "October to March. It is very hot the rest of the year.", howToGet: "Fly from Cairo or Luxor, or sail a Nile cruise between Luxor and Aswan.", whereToStay: "Along the Corniche for Nile views; Elephantine Island for quiet.", tips: "Abu Simbel departs very early, so plan a rest afternoon after.", recommendedDays: "2 days" },
  { slug: "alexandria", name: "Alexandria", tagline: "Mediterranean Egypt", overview: "A sea-breeze contrast to Cairo: the Bibliotheca Alexandrina, Qaitbay Citadel, catacombs and fresh seafood on the corniche.", bestTime: "April to June and September to November.", howToGet: "About 2.5–3 hours from Cairo by road, or a train.", whereToStay: "Along the corniche in the city centre.", tips: "Ideal as a long day trip from Cairo, but an overnight lets you enjoy the evenings.", recommendedDays: "1–2 days" },
  { slug: "hurghada", name: "Hurghada", tagline: "Red Sea reefs and desert quads", overview: "A Red Sea base for snorkelling and diving trips to the Giftun islands, plus desert safaris.", bestTime: "Year-round; sea is warmest June to October.", howToGet: "Direct flights from Europe and Cairo; road transfer from Luxor is about 4–5 hours.", whereToStay: "El Gouna for a polished resort town, Sahl Hasheesh for beach resorts, central Hurghada for value.", tips: "Bring reef-safe sunscreen and confirm boat size and lunch when you book.", recommendedDays: "3–5 days" },
].map((d) => ({ ...d, seoTitle: `${d.name} Tours and Travel Guide | Egypt Knight`, seoDescription: `${d.tagline}. Plan ${d.name} with local experts: best time to visit, where to stay and the tours worth booking.` }));

type T = { slug: string; title: string; dest: string; cat: string; aud?: string; days?: number; hours?: number; level?: string; price: number; disc?: number; priv?: number; model?: string; short: string; long: string; hl: string[]; it: { title: string; text: string }[]; inc: string[]; exc: string[]; pop: number };
const tours: T[] = [
  { slug: "giza-pyramids-sphinx-day-tour", title: "Giza Pyramids and Sphinx Day Tour", dest: "giza", cat: "DAY", hours: 6, price: 55, priv: 60, pop: 95, short: "The big three, planned so you skip the worst of the crowds and heat.", long: "Start early at the Giza Plateau with a licensed Egyptologist guide (guide licences to be confirmed by Egypt Knight). We time the Great Pyramid, the panoramic viewpoint and the Sphinx around the crowds, then finish with a relaxed lunch stop.", hl: ["Great Pyramid and Sphinx with an Egyptologist guide", "Panoramic viewpoint for photos", "Air-conditioned vehicle", "Hotel pickup in Cairo/Giza"], it: [{ title: "Hotel pickup", text: "Your driver meets you in the lobby in the early morning." }, { title: "Giza Plateau", text: "Walk the pyramids area and enter the Sphinx enclosure." }, { title: "Panorama point", text: "Best photo spot for all three pyramids." }, { title: "Lunch and return", text: "Optional lunch stop, then drop-off at your hotel." }], inc: ["Hotel pickup and drop-off", "Egyptologist guide", "Air-conditioned vehicle", "Bottled water"], exc: ["Entrance fees", "Lunch", "Tips", "Camel or horse rides"] },
  { slug: "grand-egyptian-museum-pyramids-private-day", title: "Grand Egyptian Museum and Pyramids Private Day", dest: "giza", cat: "DAY", aud: "FAMILY", hours: 9, price: 120, priv: 0, model: "PER_GROUP", pop: 88, short: "Museum in the morning, pyramids in the afternoon, at your family's pace.", long: "A private day for families and small groups: the Grand Egyptian Museum's galleries with a guide who keeps it lively for kids, then the pyramids when the afternoon light is softer.", hl: ["Private guide and vehicle", "Kid-friendly storytelling", "Flexible pace and breaks"], it: [{ title: "Grand Egyptian Museum", text: "Highlights tour with time to linger." }, { title: "Lunch", text: "Break at a family-friendly restaurant." }, { title: "Pyramids", text: "Golden-hour visit to the plateau." }], inc: ["Private vehicle and driver", "Private Egyptologist guide", "Hotel pickup"], exc: ["Entrance fees", "Lunch", "Tips"] },
  { slug: "cairo-old-town-coptic-islamic-khan-el-khalili", title: "Old Cairo: Coptic, Islamic and Khan el-Khalili", dest: "cairo", cat: "DAY", aud: "FRIENDS", hours: 7, price: 45, pop: 70, short: "The Cairo most visitors miss: churches, mosques and the bazaar.", long: "Walk through Coptic Cairo's Hanging Church, see Islamic Cairo's Al-Muizz street and finish with tea in Khan el-Khalili. Good for friends and curious first-timers.", hl: ["Coptic Cairo", "Islamic Cairo highlights", "Khan el-Khalili bazaar time", "Local tea stop"], it: [{ title: "Coptic Cairo", text: "Churches and the old Roman fortress area." }, { title: "Islamic Cairo", text: "Historic mosques and Al-Muizz street." }, { title: "Khan el-Khalili", text: "Free time in the bazaar." }], inc: ["Guide", "Vehicle", "Bottled water"], exc: ["Entrance fees", "Lunch", "Tips"] },
  { slug: "luxor-east-and-west-bank-day-tour", title: "Luxor East and West Bank Day Tour", dest: "luxor", cat: "DAY", hours: 10, level: "MODERATE", price: 85, priv: 50, pop: 90, short: "Karnak, Luxor Temple, the Valley of the Kings and Hatshepsut in one big day.", long: "Cover Luxor's headline sites with a guide who explains what you are looking at. We start on the west bank early, before the tombs get hot, then cross to Karnak and Luxor Temple.", hl: ["Valley of the Kings", "Hatshepsut Temple", "Karnak and Luxor Temple", "Colossi of Memnon"], it: [{ title: "West bank", text: "Valley of the Kings, Hatshepsut Temple, Colossi of Memnon." }, { title: "Lunch", text: "Local restaurant stop." }, { title: "East bank", text: "Karnak and Luxor Temple." }], inc: ["Guide", "Air-conditioned vehicle", "Water"], exc: ["Entrance fees", "Lunch", "Tips"] },
  { slug: "luxor-sunrise-hot-air-balloon", title: "Luxor Sunrise Hot Air Balloon Flight", dest: "luxor", cat: "DAY", aud: "COUPLE", hours: 4, price: 95, pop: 75, short: "Float over the west bank temples as the sun comes up.", long: "A sunrise balloon over Luxor's west bank. A great add-on to a Luxor day tour and popular with couples and honeymooners. Flights depend on weather.", hl: ["Sunrise flight", "Hotel pickup", "Weather-dependent, with rebooking"], it: [{ title: "Early pickup", text: "Transfer to the launch site before dawn." }, { title: "Flight", text: "Approximately 45 minutes in the air." }, { title: "Return", text: "Back to your hotel for breakfast." }], inc: ["Hotel pickup", "Flight", "Basic snack"], exc: ["Tips", "Photos"] },
  { slug: "aswan-philae-and-abu-simbel-day", title: "Aswan: Philae Temple and Abu Simbel Day", dest: "aswan", cat: "DAY", hours: 12, level: "MODERATE", price: 110, pop: 68, short: "Ramses II's giant temples and Philae by boat, in one long day.", long: "An early start for the drive to Abu Simbel, then back to Aswan for Philae Temple by boat. It is a long day, but the two temples are the highlight of the south.", hl: ["Abu Simbel", "Philae Temple by boat"], it: [{ title: "Early departure", text: "Convoy drive to Abu Simbel." }, { title: "Abu Simbel", text: "Explore both temples." }, { title: "Philae", text: "Boat ride and temple visit in the afternoon." }], inc: ["Guide", "Vehicle", "Boat to Philae"], exc: ["Entrance fees", "Lunch", "Tips"] },
  { slug: "5-day-cairo-and-luxor-package", title: "5-Day Cairo and Luxor Package", dest: "cairo", cat: "MULTI_DAY", aud: "COUPLE", days: 5, hours: 8, price: 650, priv: 180, pop: 92, short: "Pyramids, museums and Luxor's temples with flights between, all arranged.", long: "Two days in Cairo, a short flight south, and two days in Luxor. Hotels, transfers, guides and domestic flights can be included; final inclusions are confirmed on quote.", hl: ["Cairo and Giza", "Luxor east and west bank", "Domestic flight", "Airport transfers"], it: [{ title: "Day 1: Arrive in Cairo", text: "Airport pickup and hotel check-in." }, { title: "Day 2: Giza and Museum", text: "Pyramids, Sphinx and museum time." }, { title: "Day 3: Fly to Luxor", text: "Karnak and Luxor Temple in the evening." }, { title: "Day 4: West bank", text: "Valley of the Kings and Hatshepsut." }, { title: "Day 5: Departure", text: "Transfer for your flight." }], inc: ["4 nights hotel (confirmed on quote)", "Airport transfers", "Guides", "Domestic flight"], exc: ["International flights", "Entrance fees unless stated", "Tips"] },
  { slug: "cairo-airport-transfer", title: "Cairo Airport Private Transfer", dest: "cairo", cat: "TRANSFER", hours: 1, price: 25, model: "PER_GROUP", pop: 80, short: "Meet-and-greet at CAI, fixed price to your hotel.", long: "A driver meets you at arrivals with your name on a sign, helps with bags and drives you to your hotel in Cairo or Giza. Flight tracking means you are not left waiting.", hl: ["Meet and greet", "Flight tracking", "Fixed price"], it: [{ title: "Arrival", text: "Driver meets you at arrivals." }, { title: "Transfer", text: "Direct drive to your hotel." }], inc: ["Driver", "Vehicle", "Waiting time for flight delays"], exc: ["Tips"] },
];

export async function seedDatabase() {
  const adminEmail = (process.env.ADMIN_EMAIL || "admin@egyptknight.example").toLowerCase();
  const adminPass = process.env.ADMIN_PASSWORD || (process.env.NODE_ENV === "production" ? "" : "change-me-now");
  if (adminPass) {
    const ex = await db.select().from(s.users).where(eq(s.users.email, adminEmail));
    if (!ex.length) await db.insert(s.users).values({ email: adminEmail, name: "Admin", passwordHash: await bcrypt.hash(adminPass, 12), role: "SUPER_ADMIN" });
  } else console.warn("ADMIN_PASSWORD not set: no admin user created");

  for (const d of dests) {
    if (!(await db.select().from(s.destinations).where(eq(s.destinations.slug, d.slug))).length) await db.insert(s.destinations).values(d);
  }
  const destRows = await db.select().from(s.destinations);
  const dmap = Object.fromEntries(destRows.map((d) => [d.slug, d.id]));
  for (const t of tours) {
    if ((await db.select().from(s.tours).where(eq(s.tours.slug, t.slug))).length) continue;
    const [row] = await db.insert(s.tours).values({
      slug: t.slug, title: t.title, shortDescription: t.short, longDescription: t.long, destinationId: dmap[t.dest],
      category: t.cat, audience: t.aud ?? "ALL", durationHours: t.hours ?? 8, durationDays: t.days ?? 1, activityLevel: t.level ?? "EASY",
      pricingModel: t.model ?? "PER_PERSON", price: t.price, discountPrice: t.disc ?? null, privateSurcharge: t.priv ?? 0,
      isPrivateAvailable: (t.priv ?? 0) > 0 || t.model === "PER_GROUP", maxTravelers: t.model === "PER_GROUP" ? 6 : 12,
      highlights: JSON.stringify(t.hl), itinerary: JSON.stringify(t.it), included: JSON.stringify(t.inc), excluded: JSON.stringify(t.exc),
      pickupInfo: "Hotel pickup in Cairo, Giza or Luxor. Exact time is confirmed the day before.", meetingPoint: "Your hotel lobby, or the meeting point we send you on WhatsApp.",
      whatToBring: "Comfortable shoes, sun hat, sunscreen, water bottle, a light layer for mornings.",
      cancellationPolicy: "Free cancellation up to 24 hours before the start time (policy to be confirmed by Egypt Knight).",
      faqs: JSON.stringify([{ q: "Is hotel pickup included?", a: "Yes for Cairo, Giza and Luxor hotels. Tell us where you're staying when you book." }, { q: "Can we change the date?", a: "Message us on WhatsApp and we will move you if space allows." }]),
      seoTitle: `${t.title} | Egypt Knight`.slice(0, 70), seoDescription: t.short.slice(0, 160), status: "PUBLISHED", popularity: t.pop,
    }).returning();
    await db.insert(s.addons).values([
      { tourId: row.id, name: "Airport pickup", description: "Meet-and-greet transfer from the airport", price: 25, unit: "PER_BOOKING" },
      { tourId: row.id, name: "Lunch at a local restaurant", description: "Set lunch with soft drink", price: 12, unit: "PER_PERSON" },
      { tourId: row.id, name: "Professional photographer", description: "One hour of photos at the main site", price: 60, unit: "PER_BOOKING" },
    ]);
  }
  if (!(await db.select().from(s.coupons).where(eq(s.coupons.code, "WELCOME10"))).length)
    await db.insert(s.coupons).values({ code: "WELCOME10", type: "PERCENT", value: 10, minSubtotal: 50, firstBookingOnly: true, maxUses: 500 });
  if (!(await db.select().from(s.guides)).length) await db.insert(s.guides).values([
    { slug: "best-time-to-visit-egypt", title: "Best Time to Visit Egypt", cluster: "Egypt Travel Guide", summary: "Month-by-month advice for Cairo, Luxor, Aswan and the Red Sea.", destinationSlug: "cairo", seoTitle: "Best Time to Visit Egypt, Month by Month", seoDescription: "When to go to Egypt for pleasant weather, smaller crowds and the best Red Sea conditions.", status: "PUBLISHED",
      body: "Egypt's sweet spot is October to April, when Cairo, Luxor and Aswan are comfortable for sightseeing.\n\nSummers are hot, especially in Upper Egypt. If you travel then, do temples and tombs at sunrise and rest in the afternoon.\n\nThe Red Sea (Hurghada, Sharm El Sheikh, Dahab) is good all year, with the warmest water from June to October.\n\nTip: Christmas and Easter are the busiest periods. Book Luxor and Nile cruises early." },
    { slug: "egypt-visa-guide", title: "Egypt Visa Guide", cluster: "Egypt Travel Guide", summary: "How visas work for most visitors, and what to check before you fly.", destinationSlug: null, seoTitle: "Egypt Visa Guide for Tourists", seoDescription: "What to know about tourist visas for Egypt, e-visa and visa on arrival, and what to check before you travel.", status: "PUBLISHED",
      body: "Many nationalities can get a tourist visa on arrival or through the official e-visa portal, but rules and fees change and depend on your passport.\n\nAlways confirm current requirements on Egypt's official e-visa website or with your embassy before you fly. Your passport should have at least six months of validity.\n\nIf you booked a transfer with us, tell us your flight number and we will track it so your driver is there when you clear immigration." },
    { slug: "egypt-3-day-itinerary", title: "Egypt in 3 Days: A Cairo Itinerary", cluster: "Itineraries", summary: "A realistic first-timer's plan for a short stop in Cairo.", destinationSlug: "cairo", seoTitle: "Egypt 3-Day Itinerary (Cairo and Giza)", seoDescription: "A practical 3-day Egypt itinerary: pyramids, museum time, Old Cairo and the bazaar.", status: "PUBLISHED",
      body: "Day 1: Giza. Pyramids and Sphinx early, museum in the afternoon.\n\nDay 2: Old Cairo. Coptic Cairo, Islamic Cairo and Khan el-Khalili.\n\nDay 3: Choose: Saqqara and Memphis for early pyramids, or Alexandria for a change of scene.\n\nWant Luxor too? A 5-day plan with a short flight fits more in without rushing." },
  ]);
  console.log("Seed complete. Admin:", adminEmail);
}
