import type { Metadata } from "next";
import LegalPage from "@/components/LegalPage";
import { getSettings } from "@/lib/settings";
export const dynamic = "force-dynamic";
export const metadata: Metadata = { title: "Privacy Policy", description: "How Egypt Knight Tours collects, uses, protects and deletes your personal data, including passport details for travel arrangements.", alternates: { canonical: "/privacy-policy" } };
export default async function Privacy() {
  const g = await getSettings(); const co = g["company.name"]; const mail = g["company.email"];
  return <LegalPage eyebrow="Legal" title="Privacy Policy" updated="September 2026" intro={`${co} ("we", "us") arranges tours, transfers and trips in Egypt. This policy explains what personal data we collect when you use our website or book with us, why we collect it, how we protect it, and the choices you have.`}
    sections={[
      { h: "Who we are", p: [`${co} is the operator of this website and the business that arranges your trip. You can contact us about your data at ${mail}${g["company.whatsapp"] ? ` or on WhatsApp at ${g["company.whatsapp"]}` : ""}.`] },
      { h: "The data we collect", items: ["Contact details: your name, email address, phone or WhatsApp number and country.", "Booking details: the tour, dates, number of travellers, pickup location, requests, dietary or accessibility needs and preferred language.", "Traveller details needed for travel arrangements: nationality, date of birth, and passport details and scans, where we need them to arrange hotels, flights, permits or entry.", "Payment information: which payments you made and when. We do not store card numbers on this website.", "Messages you send us by form, email or WhatsApp.", "Basic website usage, such as which pages and tours were viewed, so we can improve the site. We do not use advertising or cross-site tracking cookies."] },
      { h: "Why we use your data", items: ["To confirm, arrange and run your booking, including sharing details with the guides, drivers, hotels and cruise operators who deliver your trip.", "To send you invoices, itineraries, payment details and trip updates.", "To answer your questions and give support before, during and after your trip.", "To meet legal, tax and accounting obligations.", "With your permission, to send tips and offers about future trips. You can opt out at any time."] },
      { h: "Passport details and files", p: ["Passport details are used only to arrange your travel, for example hotel and cruise registration, permits and entry formalities. Passport scans you upload are encrypted when stored and can be opened only by authorised staff, and every access is logged.", "We delete passport files after your trip, normally within a short period after you return, unless the law requires us to keep them longer."] },
      { h: "Who we share data with", p: ["We share only what is needed to deliver your trip, with people and services such as your tour guide and driver, hotels and cruise operators, our payment and banking providers, and technology providers that host our website and send email. They may process data only for those purposes. We do not sell your personal data."] },
      { h: "International transfers", p: ["Our website and systems are hosted with cloud providers that may process data in other countries, including outside Egypt and your home country. We choose reputable providers and use measures such as encryption to protect your data."] },
      { h: "How long we keep data", items: ["Passport files: deleted after your trip.", "Booking and invoice records: kept for as long as needed for accounting and legal requirements.", "Enquiries and marketing preferences: kept until you ask us to stop or delete them."] },
      { h: "How we protect data", p: ["Access to our booking system is restricted to authorised staff and protected by passwords and access controls. Sensitive files are encrypted, connections use HTTPS, and we review access logs. No system is perfectly secure, but we take reasonable steps to protect your information."] },
      { h: "Your rights", p: [`Depending on where you live, you may have the right to access your data, correct it, delete it, restrict or object to our use of it, and receive a copy. To make a request, email ${mail}. We will respond as soon as we reasonably can.`] },
      { h: "Cookies and similar technologies", p: ["We use only what the site needs to work: for example, temporary storage in your browser to keep your booking form details while you complete it, and a secure session for staff who log in. We do not use advertising cookies. If we add analytics or marketing tools in the future, we will update this policy and ask for your consent where required."] },
      { h: "Children", p: ["We take bookings from adults. If you include children in a booking, you confirm you are their parent or legal guardian, or are authorised to provide their details."] },
      { h: "Changes to this policy", p: ["We may update this policy from time to time. The date at the top shows when it was last changed."] },
      { h: "Contact", p: [`Questions about privacy? Email ${mail}${g["company.address"] ? `, or write to ${g["company.address"]}` : ""}.`] },
    ]} />;
}
